# Generated by Django 2.2.3 on 2019-07-31 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0005_genre_media_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='media_type',
            new_name='media_types',
        ),
    ]
