# Generated by Django 2.2.3 on 2019-07-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinook', '0006_auto_20190731_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='albums',
            field=models.ManyToManyField(related_name='genres', through='chinook.Track', to='chinook.Album'),
        ),
    ]
